import React from 'react';
import { useLanguage } from '../../contexts/LanguageContext';

export const AccountDeletionPolicy: React.FC = () => {
  const { isRTL } = useLanguage();

  return (
    <div className="min-h-screen pt-20 pb-16">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className={`prose prose-invert max-w-none ${isRTL ? 'text-right' : 'text-left'}`}>
          <h1 className={`text-4xl font-bold text-white mb-8 ${isRTL ? 'font-arabic' : ''}`}>
            Account Deletion Policy
          </h1>
          
          <p className="text-white/80 text-lg mb-6">
            <strong>Last updated:</strong> {new Date().toLocaleDateString()}
          </p>

          <div className="text-white/80 leading-relaxed text-lg space-y-6">
            <p>
              At fead.app, we recognize and respect your fundamental right to control your personal information and make decisions about your digital footprint, which includes the ability to completely remove your account and all associated data from our AI-powered Instagram customer support automation platform at any time and for any reason. This Account Deletion Policy provides comprehensive information about the procedures, timelines, implications, and safeguards involved in permanently deleting your account, ensuring you have complete understanding of the process and its consequences before making this irreversible decision. We have designed our account deletion procedures to be straightforward, transparent, and user-friendly while maintaining appropriate security measures to protect against unauthorized deletion requests and ensuring compliance with legal requirements that may necessitate temporary data retention for specific purposes such as fraud prevention, legal compliance, and financial record-keeping that protect both you and our platform from potential issues that could arise from immediate, complete data destruction.
            </p>

            <p>
              The account deletion process can be initiated through multiple convenient methods designed to accommodate your preferences and ensure you can access deletion tools even if you experience difficulties with your primary account access methods. You can request account deletion directly through your account dashboard by navigating to the privacy and security settings section where you will find clearly labeled account deletion tools with step-by-step guidance through the entire process, including important warnings about data loss and irreversibility of the action. Alternatively, you can contact our dedicated privacy and data protection team by sending an email to privacy@fead.app with your account deletion request, including your registered email address, account username, and any additional information that helps us verify your identity and ensure the request is legitimate and authorized. For users who prefer direct communication or have specific concerns about the deletion process, you can contact our customer support team through the help center, live chat system when available, or phone support during business hours, and our trained representatives will guide you through the deletion process while ensuring you understand all implications and alternatives that might better serve your needs.
            </p>

            <p>
              Before proceeding with account deletion, we strongly encourage you to carefully consider the permanent and irreversible nature of this action, as well as several alternative options that might address your concerns without requiring complete account removal from our platform. Account deletion will permanently remove all your customer conversation histories, AI training data that has been customized for your specific business needs, analytics reports and performance metrics that track your customer support effectiveness over time, saved automation templates and response configurations, integration settings with your Instagram Business Account, billing history and subscription information beyond what we are legally required to retain, and any custom AI model improvements that have been developed specifically for your account through our machine learning processes. Alternative options include temporarily deactivating your account, which suspends all services while preserving your data for potential future reactivation, downgrading to a free or lower-tier plan that reduces costs while maintaining basic functionality, adjusting your privacy settings to limit data collection and processing without deleting existing information, or modifying your subscription to pause billing cycles during periods when you do not need our services, allowing you to maintain your account setup and data while avoiding ongoing costs.
            </p>

            <p>
              Upon receiving your account deletion request through any of our authorized channels, we initiate a comprehensive verification process designed to confirm your identity and ensure the deletion request is legitimate, authorized, and intentional rather than the result of account compromise, social engineering, or other security threats that could result in unintended data loss. This verification process includes confirming your identity through multiple authentication factors such as password verification, email confirmation sent to your registered address, security question responses, and potentially additional verification steps if we detect any unusual account activity or security concerns that warrant extra caution. We also implement a mandatory waiting period, typically 30 days from the initial deletion request, during which your account remains active but scheduled for deletion, giving you time to reconsider the decision, retrieve any important data you may need for business continuity purposes, or cancel the deletion request if you change your mind about leaving our platform. During this waiting period, you retain full access to all account features and can export your data, download conversation histories, save important analytics reports, and ensure you have captured any information you may need for your records or future business operations.
            </p>

            <p>
              The technical implementation of account deletion involves multiple stages designed to ensure complete removal of your personal information while respecting legal retention requirements and maintaining the integrity of our platform for other users who may have interacted with your account or data through legitimate platform functions. The deletion process begins with immediate deactivation of your account access, preventing any further use of our services while maintaining data temporarily for the completion of the deletion procedure and any necessary data export or verification processes you may require during the waiting period. We then proceed with systematic removal of your personal information from our active databases, including account profile information, contact details, authentication credentials, and any personally identifiable information that directly connects to your individual identity or business entity. Customer conversation data that contains personal information is anonymized or deleted according to your preferences and applicable privacy regulations, though certain conversation patterns may be retained in anonymized form for continued AI model improvement that benefits all platform users without compromising your privacy or revealing any identifiable information about your specific business or customers.
            </p>

            <p>
              Legal and regulatory requirements may necessitate the temporary retention of certain categories of information even after account deletion, particularly data related to financial transactions, billing records, tax documentation, fraud prevention measures, and legal compliance obligations that protect both individual users and our platform from potential regulatory issues, financial discrepancies, or security threats that could emerge after account closure. Financial records including billing history, payment information, subscription details, and tax-related documentation are typically retained for periods required by applicable accounting standards and tax regulations, usually ranging from three to seven years depending on the jurisdiction and specific regulatory requirements that govern our business operations. Security logs, fraud prevention data, and records of policy violations may be retained for longer periods to protect our platform and other users from recurring security threats, abuse patterns, or legal issues that could affect the broader user community, though all such retained information is stored securely with restricted access and is subject to the same high-level security measures that protect active user data throughout our platform infrastructure.
            </p>

            <p>
              Third-party integrations and external data sharing arrangements are carefully managed during the account deletion process to ensure your information is also removed or anonymized in connected systems and services that may have received your data through legitimate platform operations or authorized integrations during your active use of our services. This includes coordinating with Instagram's API systems to revoke authentication tokens and remove stored integration data, notifying any authorized third-party services that may have processed your data through our platform integrations, and ensuring that business partners, service providers, and data processors who have handled your information on our behalf are instructed to delete or anonymize your data according to their contractual obligations and applicable privacy requirements. We maintain detailed records of all third-party data sharing arrangements and systematically coordinate deletion activities to ensure comprehensive removal of your information across all systems and services that may have been involved in processing your data during your time as an active user of our AI-powered customer support automation platform.
            </p>

            <p>
              Data recovery and restoration options are extremely limited once the account deletion process is complete, reflecting the permanent and irreversible nature of this action that is designed to give you complete control over your digital footprint and ensure your privacy preferences are respected in the most comprehensive way possible. During the waiting period before final deletion, you can cancel the deletion request and restore full account functionality with all data intact, but once the final deletion process is executed, we cannot recover your account information, conversation histories, customized AI models, or any other data that has been permanently removed from our systems. In exceptional circumstances involving technical errors, legal requirements, or other extraordinary situations that warrant data recovery efforts, we may be able to restore limited information from backup systems for a brief period immediately following deletion, but such recovery efforts are not guaranteed, may be incomplete, and are subject to technical feasibility, legal constraints, and the specific circumstances surrounding your deletion request and any subsequent recovery needs that may arise.
            </p>

            <p>
              We continuously review and update our account deletion procedures to ensure they remain compliant with evolving privacy regulations, reflect best practices in data protection and user rights, and incorporate improvements based on user feedback and technological advances that enhance the security, efficiency, and user experience of the deletion process. If you have questions, concerns, or need assistance with account deletion, our privacy team is available through privacy@fead.app to provide detailed guidance, address specific concerns about the deletion process, explain the implications of account removal for your particular use case, and help you explore alternative options that might better serve your needs while respecting your privacy preferences and business requirements. We are committed to making account deletion as straightforward and transparent as possible while ensuring you have all the information and support you need to make informed decisions about your data and privacy on our AI-powered Instagram customer support automation platform, and we will continue to enhance these procedures based on user feedback and regulatory developments in the evolving landscape of digital privacy rights and data protection.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};