import React from 'react';
import { useLanguage } from '../../contexts/LanguageContext';

export const PrivacyPolicy: React.FC = () => {
  const { isRTL } = useLanguage();

  return (
    <div className="min-h-screen pt-20 pb-16">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className={`prose prose-invert max-w-none ${isRTL ? 'text-right' : 'text-left'}`}>
          <h1 className={`text-4xl font-bold text-white mb-8 ${isRTL ? 'font-arabic' : ''}`}>
            Privacy Policy
          </h1>
          
          <p className="text-white/80 text-lg mb-6">
            <strong>Last updated:</strong> {new Date().toLocaleDateString()}
          </p>

          <div className="text-white/80 leading-relaxed text-lg space-y-6">
            <p>
              At fead.app, we are deeply committed to protecting your privacy and ensuring the comprehensive security of all personal information you entrust to us through our sophisticated AI-powered Instagram customer support automation platform. This Privacy Policy serves as a detailed explanation of our data practices, outlining precisely how we collect, process, utilize, store, and safeguard your valuable data throughout your journey with our innovative service. We understand that trust is the foundation of any successful business relationship, and we have designed our privacy framework to exceed industry standards while maintaining complete transparency about our operations. Our commitment extends to implementing cutting-edge security measures, adhering to international data protection regulations, and continuously evolving our practices to address emerging privacy challenges in the rapidly advancing field of artificial intelligence and social media automation.
            </p>

            <p>
              When you engage with our platform, we collect various categories of information necessary to provide you with exceptional AI-powered customer support services. This includes your fundamental account information such as your email address, username, comprehensive organization details, business profile information, and securely encrypted authentication credentials that protect your account from unauthorized access. Additionally, we process Instagram-specific data through official API integrations, including your Instagram Business Account information, direct messages and comments that require AI analysis for automated responses, complete customer interaction history to maintain conversation continuity, and detailed response analytics and performance metrics that help optimize your customer support effectiveness. Our AI processing systems also require access to customer inquiries and messages for natural language understanding, AI-generated response suggestions that maintain your brand voice, comprehensive conversation context and history to ensure coherent multi-turn interactions, and sophisticated learning patterns that continuously improve AI performance while respecting privacy boundaries. We maintain strict data minimization principles, ensuring we only collect and process information that is absolutely necessary for delivering our core services and enhancing your customer support automation experience.
            </p>

            <p>
              Our utilization of your data centers primarily around powering our advanced AI agent operations and continuously improving our service quality to better serve your business needs. The AI systems analyze customer messages using state-of-the-art natural language processing techniques to generate contextually appropriate, brand-consistent responses that maintain the authentic voice of your business while providing instant, accurate support to your customers. These systems learn from conversation patterns through sophisticated machine learning algorithms to continuously improve response quality, accuracy, and relevance, ensuring your customers receive increasingly better support over time. Our platform provides 24/7 automated customer support capabilities that never sleep, handling inquiries across different time zones and languages while maintaining conversation context for coherent, meaningful interactions that feel natural and helpful. For service improvement purposes, we monitor AI performance and accuracy through comprehensive analytics, analyze usage patterns to identify opportunities for feature enhancements, provide personalized dashboard insights that help you understand your customer support performance, and generate detailed performance reports that enable data-driven decision making for your business growth.
            </p>

            <p>
              Our AI data processing standards reflect our commitment to ethical artificial intelligence and responsible data handling practices that prioritize your privacy while delivering exceptional service quality. We implement strict data minimization protocols, processing only the absolute minimum data necessary for AI operations and customer support automation, ensuring no unnecessary personal information is stored or analyzed. Purpose limitation principles guide all our data processing activities, meaning customer data is used exclusively for providing automated support services, improving AI response quality, and enhancing platform functionality, never for unrelated commercial purposes or third-party marketing. We maintain rigorous accuracy and quality standards through continuous monitoring systems that ensure AI responses are accurate, relevant, contextually appropriate, and aligned with your business values and customer service standards. Human oversight remains a cornerstone of our AI operations, with qualified personnel regularly reviewing AI performance, maintaining the ability to intervene and override automated decisions when necessary, and ensuring all AI interactions meet our high standards for customer service excellence and ethical AI deployment.
            </p>

            <p>
              Data security and protection form the bedrock of our platform architecture, with multiple layers of advanced security measures protecting your information at every stage of processing and storage. All data transmission occurs through industry-leading TLS 1.3 encryption protocols, ensuring your information remains secure during transfer between your systems and our servers, while data at rest is protected using military-grade AES-256 encryption that renders it unreadable to unauthorized parties. Our API communications utilize end-to-end encryption methodologies that prevent interception and tampering during data exchange processes. Access control systems implement multi-factor authentication for all user accounts, role-based access control (RBAC) that ensures personnel only access data necessary for their specific responsibilities, regular comprehensive security audits conducted by independent security firms, and automated threat detection systems that continuously monitor for suspicious activities and potential security breaches. AI model security receives special attention through isolated processing environments that prevent unauthorized access to your data during AI training and inference, regular model validation and testing to ensure continued security and performance, sophisticated bias detection and mitigation protocols that prevent discriminatory or inappropriate responses, and secure model deployment practices that protect proprietary algorithms and customer data throughout the AI lifecycle.
            </p>

            <p>
              Our data retention and deletion policies balance the need for service continuity and improvement with respect for your privacy rights and data minimization principles. Customer conversation data is retained for a maximum of two years to enable continuous service improvement and AI model refinement, after which it is securely deleted from our systems unless specifically required for legal compliance purposes. AI training data undergoes anonymization processes within 30 days of collection, removing all personally identifiable information while preserving the linguistic patterns necessary for model improvement. Account data remains stored until you specifically request account deletion through your account settings or direct communication with our support team, at which point we initiate comprehensive data removal processes across all our systems and backups. Analytics data is maintained for up to three years to provide valuable business insights and long-term performance trends, but is aggregated and anonymized to prevent identification of individual users or conversations. You retain complete control over your data with the right to request immediate deletion at any time, and we provide transparent tools and processes to exercise this right effectively and completely.
            </p>

            <p>
              Third-party integrations are carefully selected and rigorously managed to ensure your data remains protected throughout all external interactions and processing activities. Our integration with Instagram's official API platform complies with all Instagram Platform Policy requirements, Meta's data use policies, and industry best practices for social media data handling, ensuring your Instagram business data is processed only according to approved use cases and with appropriate security measures. We collaborate exclusively with trusted AI service providers who meet our stringent security and privacy standards, undergo regular security assessments, and are bound by comprehensive data processing agreements that legally require them to maintain the same high level of data protection we provide directly. All third-party data processing agreements include specific provisions for data minimization, purpose limitation, security requirements, breach notification procedures, and immediate data deletion upon termination of services, ensuring your data remains protected throughout the entire ecosystem of services that power our platform.
            </p>

            <p>
              Under applicable data protection laws including GDPR, CCPA, and other regional privacy regulations, you possess comprehensive rights regarding your personal data that we fully respect and facilitate through user-friendly tools and responsive support processes. These rights include the fundamental right to access your personal data and receive detailed information about how it is being processed, the right to rectify any inaccurate information and ensure your data remains current and correct, the right to request complete data deletion and have your information permanently removed from our systems, the right to data portability allowing you to transfer your information to other services in standard formats, the right to restrict certain processing activities if you have concerns about specific uses of your data, the right to object to automated decision-making and request human review of AI-generated responses or recommendations, and the right to withdraw consent at any time for any processing activities that require your explicit consent. We provide clear, accessible mechanisms for exercising these rights through your account dashboard, dedicated privacy tools, and direct communication with our privacy team, ensuring you can easily manage your data and privacy preferences according to your specific needs and concerns.
            </p>

            <p>
              International data transfers, when necessary for service delivery or platform operation, are conducted with the highest levels of protection and legal compliance to ensure your data remains secure regardless of geographic boundaries. If you are located outside our primary data processing regions, your data may be transferred internationally to our secure data centers and trusted service providers, but we ensure all such transfers comply with applicable data protection laws through appropriate legal safeguards such as Standard Contractual Clauses approved by relevant data protection authorities, adequacy decisions recognizing equivalent protection levels in destination countries, and binding corporate rules that ensure consistent high-level protection across all jurisdictions where your data may be processed. We continuously monitor international privacy law developments and adapt our transfer mechanisms to ensure ongoing compliance and maximum protection for your personal information regardless of where processing occurs.
            </p>

            <p>
              For any questions, concerns, or requests regarding this Privacy Policy, our data practices, or your privacy rights, we encourage you to contact us through multiple convenient channels designed to provide prompt, comprehensive responses to all privacy-related inquiries. You can reach our dedicated privacy team at privacy@fead.app for general privacy questions and policy clarifications, contact our Data Protection Officer directly at dpo@fead.app for formal privacy rights requests and detailed privacy consultations, or reach us by mail at our business address for written correspondence and formal legal notifications. Our privacy team is committed to responding to all inquiries within 48 hours and resolving privacy concerns as quickly and thoroughly as possible while maintaining complete confidentiality and professionalism throughout the process.
            </p>

            <p>
              We may periodically update this Privacy Policy to reflect changes in our data practices, new features and services, evolving legal requirements, or improvements in privacy protection technologies, always striving to enhance your privacy protection while maintaining transparency about our operations. When we make material changes that could affect your rights or how your data is processed, we will notify you through multiple channels including email notifications sent to your registered address, prominent notices in your account dashboard, and updates to the "Last updated" date displayed prominently at the top of this policy document. We encourage you to review this Privacy Policy periodically to stay informed about our latest privacy practices and any changes that might affect your use of our services. Your continued use of our platform following the posting of any updates to this Privacy Policy constitutes your acceptance of those changes, though we will always seek additional explicit consent for any changes that materially expand our use of your personal data beyond the scope originally agreed upon when you first joined our platform.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};