import React from 'react';
import { useLanguage } from '../../contexts/LanguageContext';

export const TermsAndConditions: React.FC = () => {
  const { isRTL } = useLanguage();

  return (
    <div className="min-h-screen pt-20 pb-16">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className={`prose prose-invert max-w-none ${isRTL ? 'text-right' : 'text-left'}`}>
          <h1 className={`text-4xl font-bold text-white mb-8 ${isRTL ? 'font-arabic' : ''}`}>
            Terms of Service
          </h1>
          
          <p className="text-white/80 text-lg mb-6">
            <strong>Last updated:</strong> {new Date().toLocaleDateString()}
          </p>

          <div className="text-white/80 leading-relaxed text-lg space-y-6">
            <p>
              Welcome to fead.app, the premier AI-powered Instagram customer support automation platform designed to revolutionize how businesses interact with their customers through intelligent, responsive, and efficient automated support systems. These Terms of Service constitute a legally binding agreement between you, whether as an individual user or representing a business entity, and fead.app, governing your access to and use of our comprehensive suite of AI-driven customer support tools, services, features, and platform capabilities. By creating an account, accessing our platform, or utilizing any of our services, you acknowledge that you have carefully read, fully understood, and agree to be bound by all terms and conditions outlined in this agreement, as well as our Privacy Policy and any additional terms that may apply to specific features or services within our platform. Your acceptance of these terms creates a contractual relationship that enables us to provide you with cutting-edge AI technology while establishing clear expectations and responsibilities for all parties involved in this innovative customer support ecosystem.
            </p>

            <p>
              Our platform provides sophisticated artificial intelligence-powered automation tools specifically designed for Instagram customer support, enabling businesses to deliver exceptional customer service experiences through advanced natural language processing, machine learning algorithms, and intelligent response generation systems that work seamlessly with Instagram's messaging infrastructure. The services include but are not limited to automated customer inquiry processing and response generation, intelligent conversation management that maintains context across multiple interactions, comprehensive analytics and reporting dashboards that provide insights into customer support performance, business integration tools that connect with your existing workflows and systems, multi-language support capabilities for global customer bases, 24/7 automated response systems that never require downtime, advanced AI training and customization features that adapt to your specific business needs and customer communication patterns, and ongoing platform improvements and feature updates that continuously enhance your customer support capabilities. These services are provided on a subscription basis with various tiers designed to accommodate businesses of all sizes, from individual entrepreneurs to large enterprises requiring sophisticated customer support automation at scale.
            </p>

            <p>
              To access and utilize our services, you must create and maintain an active account with accurate, complete, and up-to-date information including your legal name or business entity details, valid email address for account communications and important service notifications, secure password that meets our security requirements, Instagram Business Account credentials for platform integration, and any additional information required for service provision and legal compliance purposes. You are solely responsible for maintaining the confidentiality and security of your account credentials, including your password and any authentication tokens or API keys associated with your account, and you agree to immediately notify us of any suspected unauthorized access or security breaches affecting your account. You must be at least 18 years of age or the age of legal majority in your jurisdiction to enter into this agreement, and if you are representing a business entity, you must have the legal authority to bind that entity to these terms and conditions. Account sharing is strictly prohibited, and each account must correspond to a single authorized user or business entity with clearly defined usage boundaries and access controls that prevent unauthorized use of our AI services and platform features.
            </p>

            <p>
              Your use of our platform must comply with all applicable laws, regulations, and industry standards, including but not limited to data protection regulations such as GDPR, CCPA, and other privacy laws, social media platform policies and terms of service, particularly Instagram's Community Guidelines and Terms of Use, advertising and marketing regulations in your jurisdiction, consumer protection laws governing customer communications, and any specific industry regulations that apply to your business operations. You agree not to use our services for any illegal, harmful, fraudulent, or unauthorized purposes, including but not limited to sending spam or unsolicited messages through our automation tools, impersonating other individuals or entities in customer communications, collecting or attempting to collect personal information without proper consent, interfering with or disrupting our services or server infrastructure, attempting to gain unauthorized access to other user accounts or our systems, using our AI technology to generate inappropriate, offensive, or discriminatory content, or violating any intellectual property rights of third parties through your use of our platform. We reserve the right to monitor usage patterns, investigate suspicious activities, and take appropriate action including account suspension or termination for violations of these terms or applicable laws.
            </p>

            <p>
              Our AI technology and platform infrastructure, including all software, algorithms, machine learning models, user interfaces, databases, and related intellectual property, remain the exclusive property of fead.app and are protected by applicable copyright, trademark, patent, and trade secret laws. We grant you a limited, non-exclusive, non-transferable, revocable license to use our services solely for their intended purpose of Instagram customer support automation, subject to these terms and your subscription agreement. You retain ownership of all content you provide to our platform, including customer conversation data, business information, and any customization parameters you configure for your AI agents, while granting us the necessary rights to process, analyze, and utilize this information to provide our services effectively and improve our AI technology through machine learning and algorithm optimization processes. Any feedback, suggestions, or ideas you provide regarding our services may be freely used by us for platform improvement and development purposes without obligation or compensation to you, though we will always respect your privacy and confidentiality in how we implement such improvements.
            </p>

            <p>
              Our subscription-based pricing model offers various service tiers designed to accommodate different business needs, usage levels, and feature requirements, with transparent billing cycles, clear upgrade and downgrade paths, and detailed usage tracking to ensure you always understand your service costs and consumption patterns. Payment terms require that all fees be paid in advance according to your selected billing cycle, with automatic renewal unless you cancel your subscription before the renewal date through your account settings or by contacting our support team with appropriate notice. Late payments may result in service interruption, account suspension, and additional fees as outlined in your subscription agreement, though we always provide reasonable notice and opportunities to resolve payment issues before taking restrictive actions. Refunds are generally provided only in cases of service failures on our part, billing errors, or other circumstances outlined in our refund policy, with prorated refunds available for subscription cancellations under specific conditions that ensure fairness for both parties while maintaining the sustainability of our service operations.
            </p>

            <p>
              We strive to maintain high availability and reliable performance of our platform through robust infrastructure, redundant systems, and comprehensive monitoring, but like all technology services, we cannot guarantee absolute uptime or error-free operation at all times due to factors beyond our control including internet connectivity issues, third-party service dependencies, scheduled maintenance requirements, and unforeseen technical challenges. Our service level commitments are outlined in your subscription agreement and include specific uptime targets, response time goals for customer support, and procedures for reporting and resolving service issues that may affect your business operations. In the event of significant service disruptions, we provide timely communications through multiple channels including email notifications, dashboard alerts, and status page updates, along with appropriate service credits or compensation as outlined in our service level agreement. We continuously invest in improving our infrastructure reliability, implementing redundancy measures, and developing contingency plans to minimize service disruptions and ensure your customer support automation remains operational even during challenging technical circumstances.
            </p>

            <p>
              Privacy and data protection are fundamental aspects of our service, governed by our comprehensive Privacy Policy that outlines in detail how we collect, process, store, and protect your personal information and business data throughout your use of our platform. We implement industry-leading security measures including end-to-end encryption for data transmission, advanced access controls with multi-factor authentication, regular security audits and vulnerability assessments, and compliance with major data protection frameworks to ensure your information remains secure and confidential at all times. Your customer data, conversation histories, and business information are processed solely for the purpose of providing our AI-powered customer support services, with strict limitations on data sharing, comprehensive data retention policies that respect your privacy preferences, and robust procedures for data deletion and account termination that ensure complete removal of your information when requested. We maintain transparency about our data practices through detailed privacy documentation, regular policy updates, and responsive customer support for any privacy-related questions or concerns you may have about how your information is handled within our platform.
            </p>

            <p>
              Account termination can occur either through your voluntary cancellation of services or through our enforcement actions for terms violations, with different procedures and implications depending on the circumstances surrounding the termination. Voluntary cancellations can be initiated at any time through your account settings with immediate effect or scheduled for the end of your current billing cycle, allowing you to continue using services until the paid period expires while preventing future charges. Upon termination, we provide reasonable data export opportunities so you can retrieve your customer interaction histories, conversation logs, analytics data, and other information you may need for business continuity purposes, though certain data may be retained according to our privacy policy and legal requirements for specified periods after account closure. Involuntary termination due to terms violations, illegal activities, or abuse of our services may result in immediate account suspension, forfeiture of any prepaid fees, and potential legal action if warranted by the severity of the violations, though we always strive to work with users to resolve issues amicably when possible and provide appropriate warnings before taking drastic enforcement actions.
            </p>

            <p>
              These Terms of Service are governed by the laws of [Your Jurisdiction] without regard to conflict of law principles, and any disputes arising from your use of our services will be resolved through binding arbitration or appropriate court proceedings as specified in our dispute resolution procedures. We may modify these terms from time to time to reflect changes in our services, legal requirements, or business practices, with reasonable advance notice provided through email notifications, account dashboard alerts, and updates to the effective date displayed prominently on this document. Significant changes that materially affect your rights or obligations will require your explicit acceptance, while minor clarifications or updates may take effect after appropriate notice periods that give you opportunity to review and understand any modifications. If you have questions, concerns, or need assistance with any aspect of these terms or our services, please contact our support team at support@fead.app, our legal department at legal@fead.app, or reach us through the contact information provided in your account dashboard, and we will respond promptly with helpful, comprehensive answers to ensure you can make the most of our AI-powered customer support automation platform while maintaining full compliance with all applicable terms and conditions.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};